### ISSUE TITLE
Authorization issues when trying to use the library

### ISSUE THREAD

**Issue by pmvieira** [google/google-auth-library-ruby#53]
Hi.

I've been trying to use the library and unfortunately not having much success... It's probably because I'm missing something really silly, but I can't progress anymore so maybe you could help?

This is what I am doing

```
require 'google/apis/compute_v1'
require 'googleauth'

scopes = ['https://www.googleapis.com/auth/cloud-platform', 'https://www.googleapis.com/auth/compute']
authorization = Google::Auth.get_application_default(scopes)

some_headers = {}
auth = authorization.apply(some_headers)

compute = Google::Apis::ComputeV1
compute = Cont::ComputeService.new
compute.authorization = auth

compute.list_instances(myproject, project_region)
```

However, i keep getting this error a after the last line is ran:
```
2.1.6 :015 > compute.list_instances(myproject, project_region)
Google::Apis::AuthorizationError: Unauthorized
from /Users/pedrovieira/.rvm/gems/ruby-2.1.6/gems/google-api-client-0.9.pre3/lib/google/apis/core/http_command.rb:191:in `check_status'
from /Users/pedrovieira/.rvm/gems/ruby-2.1.6/gems/google-api-client-0.9.pre3/lib/google/apis/core/api_command.rb:105:in `check_status'
from /Users/pedrovieira/.rvm/gems/ruby-2.1.6/gems/google-api-client-0.9.pre3/lib/google/apis/core/http_command.rb:162:in `process_response'
from /Users/pedrovieira/.rvm/gems/ruby-2.1.6/gems/google-api-client-0.9.pre3/lib/google/apis/core/http_command.rb:261:in `execute_once'
from /Users/pedrovieira/.rvm/gems/ruby-2.1.6/gems/g .... stacktrace continues...
```

I'm stuck at this point and was hopping you could shed some light on I might be missing here.

Thanks!

**Comment by sqrrrl** [comment]
You don't need to call apply. Just use the returned credentials directly.

```ruby
require 'google/apis/compute_v1'
require 'googleauth'

scopes = ['https://www.googleapis.com/auth/cloud-platform', 'https://www.googleapis.com/auth/compute']
authorization = Google::Auth.get_application_default(scopes)
compute = Google::Apis::ComputeV1
compute = Cont::ComputeService.new
compute.authorization = authorization

compute.list_instances(myproject, project_region)
```

**Comment by pmvieira** [comment]
Fantastic! :) Thank you very much @sqrrrl , works like a charm!
