### ISSUE TITLE
can't get default credentials for use with datastore emulator

### ISSUE THREAD

**Issue by samkelly** [google/google-auth-library-ruby#72]
I am trying to use the datastore emulator locally with my rails app in development mode for testing etc.

I run the beta datastore emulator, then run `gcloud beta emulators datastore env-init` and make sure those environment variables are in my .bashrc file (and source my .bashrc file). Then I try to do the following from within Rails:

```ruby
require 'gcloud'
gcloud = Gcloud.new('[project id here]')
dataset = gcloud.datastore
```

I get the following error:

```
RuntimeError: Could not load the default credentials. Browse to
https://developers.google.com/accounts/docs/application-default-credentials
for more information

	from /home/sam/.rvm/gems/ruby-2.2.3/gems/googleauth-0.5.1/lib/googleauth.rb:119:in `get_application_default'
	from /home/sam/.rvm/gems/ruby-2.2.3/gems/gcloud-0.7.2/lib/gcloud/credentials.rb:83:in `default'
	from /home/sam/.rvm/gems/ruby-2.2.3/gems/gcloud-0.7.2/lib/gcloud/datastore.rb:62:in `datastore'
	from /home/sam/.rvm/gems/ruby-2.2.3/gems/gcloud-0.7.2/lib/gcloud.rb:106:in `datastore'
	from (irb):3
	from /home/sam/.rvm/gems/ruby-2.2.3/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /home/sam/.rvm/gems/ruby-2.2.3/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /home/sam/.rvm/gems/ruby-2.2.3/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/sam/.rvm/gems/ruby-2.2.3/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/sam/.rvm/gems/ruby-2.2.3/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:18:in `require'
	from bin/rails:18:in `<main>'
```

I was under the impression I did not need a keyfile if using the datastore emulator. If I do need a keyfile, how do I create it? The datastore emulator documentation doesn't mention this at all, and seems to suggest that merely having these environment variables in place should be enough for local clients to connect automatically.

Please advise!

**Comment by samkelly** [comment]
For reference, feel free to also check out / answer the related stackoverflow post on this issue: http://stackoverflow.com/questions/36389983/cant-use-google-datastore-emulator-from-within-ruby-on-rails-project

**Comment by samkelly** [comment]
https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/610Question was answered here:
